#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2022.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Sun Dec 11 04:50:30 CET 2022
# SW Build 3526262 on Mon Apr 18 15:47:01 MDT 2022
#
# IP Build 3524634 on Mon Apr 18 20:55:01 MDT 2022
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim datapath_tb_behav -key {Behavioral:sim_1:Functional:datapath_tb} -tclbatch datapath_tb.tcl -view /home/asier/vivadoprojects/project_2/datapath_tb_behav.wcfg -view /home/asier/vivadoprojects/project_2/datapath_tb_tests.wcfg -view /home/asier/vivadoprojects/project_2/datapath_tb_WesteTest.wcfg -log simulate.log"
xsim datapath_tb_behav -key {Behavioral:sim_1:Functional:datapath_tb} -tclbatch datapath_tb.tcl -view /home/asier/vivadoprojects/project_2/datapath_tb_behav.wcfg -view /home/asier/vivadoprojects/project_2/datapath_tb_tests.wcfg -view /home/asier/vivadoprojects/project_2/datapath_tb_WesteTest.wcfg -log simulate.log

